[tool.black]
line-length = 88
target-version = ["py311"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
known_first_party = ["src"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
order_by_type = false

[tool.ruff]
exclude = [
  ".venv",
  "venv",
  "env",
  "lib",
  "site-packages",
  "dist",
  "build",
  ".mypy_cache",
  ".pytest_cache",
]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
show_error_codes = true
pretty = true
files = ["src/"]

[tool.pytest.ini_options]
addopts = "tests/ --cov=src --cov-report=term-missing"